CREATE TABLE IF NOT EXISTS LLM_Usage_Daily (
    Day DATE NOT NULL,
    UserID TEXT NOT NULL,
    BotID TEXT NOT NULL,
    IsGuest BOOLEAN NOT NULL DEFAULT FALSE,
    IsBot BOOLEAN NOT NULL DEFAULT FALSE,
    InputTokens BIGINT NOT NULL DEFAULT 0,
    OutputTokens BIGINT NOT NULL DEFAULT 0,
    Cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (Day, UserID, BotID)
);
