// Copyright (c) 2023-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import React from 'react';
import {FormattedMessage, useIntl} from 'react-intl';

import Panel from '../panel';
import {BooleanItem, ItemList, SelectionItem, SelectionItemOption} from '../item';
import {IntItem} from '../number_items';

export type ChannelJoinSummaryConfig = {
    enabled: boolean;
    bot: string;
    lookbackDays: number;
    minPosts: number;
};

/** Minimal bot shape reused from the default-bot dropdown. */
type BotOption = {
    username: string;
    displayName: string;
};

type Props = {
    value: ChannelJoinSummaryConfig;
    bots: BotOption[];
    onChange: (config: ChannelJoinSummaryConfig) => void;
};

const defaultLookbackDays = 7;
const defaultMinPosts = 3;

// ChannelJoinSummaryPanel exposes the settings for the ephemeral "catch-up"
// summary a user is shown when they join a channel. The summary is generated by
// an LLM from recent channel activity and is visible only to the joining user.
const ChannelJoinSummaryPanel = ({value, bots, onChange}: Props) => {
    const intl = useIntl();

    const handleUpdate = (patch: Partial<ChannelJoinSummaryConfig>) => {
        onChange({...value, ...patch});
    };

    return (
        <Panel
            title={<FormattedMessage defaultMessage='Channel Join Summary'/>}
            subtitle={intl.formatMessage({defaultMessage: 'Show a user a private, ephemeral catch-up summary of a channel\'s recent activity when they join it. Only the joining user sees it. Each qualifying join runs one LLM completion.'})}
        >
            <ItemList>
                <BooleanItem
                    label={intl.formatMessage({defaultMessage: 'Enable Channel Join Summary'})}
                    value={value.enabled}
                    onChange={(enabled) => handleUpdate({enabled})}
                    helpText={intl.formatMessage({defaultMessage: 'When enabled, joining a public or private channel triggers a one-time, private summary of recent messages, visible only to the joining user. Direct and group messages are never summarized.'})}
                />
                {value.enabled && (
                    <>
                        <SelectionItem
                            label={intl.formatMessage({defaultMessage: 'Summary Agent'})}
                            value={value.bot}
                            onChange={(e) => handleUpdate({bot: e.target.value})}
                        >
                            <SelectionItemOption value=''>
                                {intl.formatMessage({defaultMessage: 'First configured agent'})}
                            </SelectionItemOption>
                            {bots.map((bot) => (
                                <SelectionItemOption
                                    key={bot.username}
                                    value={bot.username}
                                >
                                    {bot.displayName}
                                </SelectionItemOption>
                            ))}
                        </SelectionItem>
                        <IntItem
                            label={intl.formatMessage({defaultMessage: 'Lookback (days)'})}
                            value={value.lookbackDays || defaultLookbackDays}
                            onChange={(lookbackDays) => handleUpdate({lookbackDays})}
                            min={1}
                            placeholder={defaultLookbackDays.toString()}
                            helptext={intl.formatMessage({defaultMessage: 'How far back the summary reaches for recent messages. Larger windows capture more history but cost more tokens.'})}
                        />
                        <IntItem
                            label={intl.formatMessage({defaultMessage: 'Minimum Messages'})}
                            value={value.minPosts || defaultMinPosts}
                            onChange={(minPosts) => handleUpdate({minPosts})}
                            min={1}
                            placeholder={defaultMinPosts.toString()}
                            helptext={intl.formatMessage({defaultMessage: 'Skip the summary when the lookback window has fewer than this many eligible messages, to avoid interrupting joins to quiet channels.'})}
                        />
                    </>
                )}
            </ItemList>
        </Panel>
    );
};

export default ChannelJoinSummaryPanel;
